id: P2084E54A
initial_creation_type: input
source_metadata:
  title: Dola Jigme Kalzang Series
  language: en
  description: 'Texts by and about Dola Jigme Kalzang (rdo bla ''jigs med skal bzang,
    b. 1789), one of the foremost disciples of Dodrupchen Jigme Trinle Özer and an
    important master in the Longchen Nyingtik tradition:'
  volume:
    781da95b3de148f5bba880b8a333e45a:
      title: 'Elucidating the Hidden Meaning: A Commentary on the Meaning of the Four
        Mudrās'
      parent: Tantra
created_at: '2022-02-28T23:01:34.427752'
last_modified_at: '2022-02-28T23:01:34.427758'
